/*
 * generated by Xtext
 */
package org.xtext.example.blorquescript.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.xtext.example.blorquescript.services.BlorqueScriptGrammarAccess;

@SuppressWarnings("all")
public class BlorqueScriptSyntacticSequencer extends AbstractSyntacticSequencer {

	protected BlorqueScriptGrammarAccess grammarAccess;
	protected AbstractElementAlias match_BSTerminalExpression_LeftParenthesisKeyword_8_0_a;
	protected AbstractElementAlias match_BSTerminalExpression_LeftParenthesisKeyword_8_0_p;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (BlorqueScriptGrammarAccess) access;
		match_BSTerminalExpression_LeftParenthesisKeyword_8_0_a = new TokenAlias(true, true, grammarAccess.getBSTerminalExpressionAccess().getLeftParenthesisKeyword_8_0());
		match_BSTerminalExpression_LeftParenthesisKeyword_8_0_p = new TokenAlias(true, false, grammarAccess.getBSTerminalExpressionAccess().getLeftParenthesisKeyword_8_0());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if(match_BSTerminalExpression_LeftParenthesisKeyword_8_0_a.equals(syntax))
				emit_BSTerminalExpression_LeftParenthesisKeyword_8_0_a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_BSTerminalExpression_LeftParenthesisKeyword_8_0_p.equals(syntax))
				emit_BSTerminalExpression_LeftParenthesisKeyword_8_0_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     '('*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) '(' castType='number'
	 *     (rule start) (ambiguity) '(' castType='object'
	 *     (rule start) (ambiguity) '(' castType='string'
	 *     (rule start) (ambiguity) 'client' ';' (rule start)
	 *     (rule start) (ambiguity) 'client' (rule start)
	 *     (rule start) (ambiguity) 'new' type=[BSClass|QualifiedName]
	 *     (rule start) (ambiguity) 'null' ';' (rule start)
	 *     (rule start) (ambiguity) 'null' (rule start)
	 *     (rule start) (ambiguity) 'this' ';' (rule start)
	 *     (rule start) (ambiguity) 'this' (rule start)
	 *     (rule start) (ambiguity) symbol=[BSSymbol|ID]
	 *     (rule start) (ambiguity) value='false'
	 *     (rule start) (ambiguity) value='true'
	 *     (rule start) (ambiguity) value=INT
	 *     (rule start) (ambiguity) value=STRING
	 *     (rule start) (ambiguity) {BSAssignment.left=}
	 *     (rule start) (ambiguity) {BSMemberSelection.receiver=}
	 */
	protected void emit_BSTerminalExpression_LeftParenthesisKeyword_8_0_a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '('+
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) '(' castType='number'
	 *     (rule start) (ambiguity) '(' castType='object'
	 *     (rule start) (ambiguity) '(' castType='string'
	 *     (rule start) (ambiguity) {BSAssignment.left=}
	 *     (rule start) (ambiguity) {BSMemberSelection.receiver=}
	 */
	protected void emit_BSTerminalExpression_LeftParenthesisKeyword_8_0_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
