/*
 * generated by Xtext
 */
package org.xtext.example.blorquescript.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BlorqueScriptUiModule extends org.xtext.example.blorquescript.ui.AbstractBlorqueScriptUiModule {
	public BlorqueScriptUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
