/*
 * generated by Xtext
 */
package org.example.blorquescript.ui.contentassist

import org.example.blorquescript.ui.contentassist.AbstractBlorqueScriptProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class BlorqueScriptProposalProvider extends AbstractBlorqueScriptProposalProvider {
}
