/*
 * generated by Xtext
 */
package org.xtext.example.blorquescript.ui.contentassist

import org.xtext.example.blorquescript.ui.contentassist.AbstractBlorqueScriptProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class BlorqueScriptProposalProvider extends AbstractBlorqueScriptProposalProvider {
}
