/*
 * generated by Xtext
 */
package org.xtext.example.blorquescript.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.blorquescript.services.BlorqueScriptGrammarAccess;

public class BlorqueScriptParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private BlorqueScriptGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.example.blorquescript.parser.antlr.internal.InternalBlorqueScriptParser createParser(XtextTokenStream stream) {
		return new org.xtext.example.blorquescript.parser.antlr.internal.InternalBlorqueScriptParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "BSFile";
	}
	
	public BlorqueScriptGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(BlorqueScriptGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
