/*
 * generated by Xtext
 */
package org.example.blorquescript;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class BlorqueScriptUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.example.blorquescript.ui.internal.BlorqueScriptActivator.getInstance().getInjector("org.example.blorquescript.BlorqueScript");
	}
	
}
