/*
 * generated by Xtext
 */
package org.example.blorquescript;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BlorqueScriptRuntimeModule extends org.example.blorquescript.AbstractBlorqueScriptRuntimeModule {

}
