/*
 * generated by Xtext
 */
package org.example.blorquescript.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractBlorqueScriptValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.example.blorquescript.blorqueScript.BlorqueScriptPackage.eINSTANCE);
		return result;
	}
}
