/*
 * generated by Xtext
 */
package org.example.blorquescript.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class BlorqueScriptAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/example/blorquescript/parser/antlr/internal/InternalBlorqueScriptParser.tokens");
	}
}
