/*
* generated by Xtext
*/
package org.xtext.example.blorquescript;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class BlorqueScriptUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.xtext.example.blorquescript.ui.internal.BlorqueScriptActivator.getInstance().getInjector("org.xtext.example.blorquescript.BlorqueScript");
	}
	
}
