/**
 * generated by Xtext
 */
package org.xtext.example.blorquescript.validation;

import org.xtext.example.blorquescript.validation.AbstractBlorqueScriptValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class BlorqueScriptValidator extends AbstractBlorqueScriptValidator {
}
